/**
 * Hand-written Kratos MDPA (`.mdpa`) ASCII serializer. Pure and vscode/WASM-free
 * so it unit-tests headless, mirroring `partsSidecar.ts`/`editOps.ts`/
 * `meshOptionsSidecar.ts`'s "pure logic module" convention — the WASM-dependent
 * extraction of `MdpaMesh` from a live gmsh model lives in `gmshService.ts`.
 *
 * MDPA has no off-the-shelf writer in any of this project's dependencies (unlike
 * every other mesh export format, which routes through Gmsh's own `gmsh.write()`)
 * — see `doc/gmsh-integration.md`'s "Kratos MDPA" section for the full spec
 * citations (block syntax, node ordering) this module was built against.
 */

export type MdpaMode = "elements" | "geometries";

export interface MdpaNode {
  /** Opaque source id (e.g. a gmsh node tag) — need not be 1-based or contiguous. */
  tag: number;
  x: number;
  y: number;
  z: number;
}

/** 4 source node tags, in the mesh generator's own local order (gmsh element type 4). */
export interface MdpaTet {
  nodeTags: [number, number, number, number];
}

/** 3 source node tags, in the mesh generator's own local order (gmsh element type 2). */
export interface MdpaTriangle {
  nodeTags: [number, number, number];
}

/** One named region (from a CAD-Preview `Part`) to emit as a Kratos SubModelPart. */
export interface MdpaGroup {
  name: string;
  /** Indices into the `tets` array passed to {@link writeMdpa}. */
  tetIndices: number[];
  /** Indices into the `triangles` array passed to {@link writeMdpa}. */
  triangleIndices: number[];
  /** Node tags from the part's own point/curve selections, beyond what its
   * tets/triangles already reference — see the node-consistency rule below. */
  extraNodeTags: number[];
}

export interface MdpaMesh {
  nodes: MdpaNode[];
  tets: MdpaTet[];
  triangles: MdpaTriangle[];
  /** Flat — this codebase's `Part[]` has no nesting concept, so SubModelParts
   * are never nested either; one top-level block per entry, in array order. */
  groups: MdpaGroup[];
}

/**
 * Serializes `mesh` to MDPA ASCII text. `"elements"` writes `Element3D4N`/
 * `SurfaceCondition3D3N` (each carrying a `prop_id`, always `0` — this codebase
 * has no material/property data) under a `Begin Properties 0` block;
 * `"geometries"` writes `Tetrahedra3D4`/`Triangle3D3` `Geometries` blocks
 * instead (no property id — the key structural difference between the two
 * modes) which, per Kratos's single `Geometries` container, **share one id
 * space** (tets get `1..T`, triangles continue `T+1..T+G`).
 *
 * Deterministic: node ids are assigned by sorting on source `tag` ascending;
 * element/condition/geometry ids by sorting each cell's own (already-
 * renumbered) node-id tuple ascending, lexicographically — so output is
 * byte-identical for the same geometry regardless of the mesh generator's
 * internal (not contractually ordered) enumeration order. A cell type with
 * zero members omits its block entirely rather than writing an empty pair.
 */
export function writeMdpa(mesh: MdpaMesh, mode: MdpaMode): string {
  const { nodeIdOf, sortedNodes } = buildNodeIdMap(mesh.nodes);
  const coordOf = (id: number): { x: number; y: number; z: number } => sortedNodes[id - 1];

  const tetIds: Array<[number, number, number, number]> = mesh.tets.map((t) =>
    orientTet(t.nodeTags.map((tag) => nodeIdOf.get(tag)!) as [number, number, number, number], coordOf)
  );
  const triIds: Array<[number, number, number]> = mesh.triangles.map(
    (t) => t.nodeTags.map((tag) => nodeIdOf.get(tag)!) as [number, number, number]
  );

  const tetAssign = assignIds(tetIds, 1);
  const triStartId = mode === "geometries" ? tetIds.length + 1 : 1;
  const triAssign = assignIds(triIds, triStartId);

  const lines: string[] = [
    "// File generated by CAD-Preview — Kratos MDPA export",
    mode === "elements" ? "// Mode: Elements + Conditions" : "// Mode: Geometries",
    "",
  ];

  if (mode === "elements") {
    lines.push("Begin Properties 0", "End Properties", "");
  }

  lines.push(...writeNodesBlock(sortedNodes), "");

  if (mode === "elements") {
    if (tetIds.length > 0) lines.push(...writeCellBlock("Elements", "Element3D4N", tetAssign, tetIds, true), "");
    if (triIds.length > 0) lines.push(...writeCellBlock("Conditions", "SurfaceCondition3D3N", triAssign, triIds, true), "");
  } else {
    if (tetIds.length > 0) lines.push(...writeCellBlock("Geometries", "Tetrahedra3D4", tetAssign, tetIds, false), "");
    if (triIds.length > 0) lines.push(...writeCellBlock("Geometries", "Triangle3D3", triAssign, triIds, false), "");
  }

  const usedNames = new Set<string>();
  for (const group of mesh.groups) {
    lines.push(...writeSubModelPartBlock(group, mode, nodeIdOf, tetIds, triIds, tetAssign.idOf, triAssign.idOf, usedNames));
  }

  return lines.join("\n").trimEnd() + "\n";
}

/** Sorts by source tag ascending and assigns dense 1-based output ids. */
function buildNodeIdMap(nodes: MdpaNode[]): { nodeIdOf: Map<number, number>; sortedNodes: MdpaNode[] } {
  const sortedNodes = [...nodes].sort((a, b) => a.tag - b.tag);
  const nodeIdOf = new Map<number, number>();
  sortedNodes.forEach((n, i) => nodeIdOf.set(n.tag, i + 1));
  return { nodeIdOf, sortedNodes };
}

/**
 * Kratos's `Tetrahedra3D4`/reference-tet node order matches the standard
 * simplex convention the mesh generator's own element type already uses (see
 * `doc/gmsh-integration.md`), so no permutation is normally needed — this is
 * a defensive backstop, not a routine correction: computes the signed volume
 * (scalar triple product of the edges from node 0) and, only if negative,
 * swaps the last two ids so every emitted tet has a positive Jacobian
 * regardless of any subtle ordering mismatch that slipped past that
 * documentation-only verification.
 */
function orientTet(
  ids: [number, number, number, number],
  coordOf: (id: number) => { x: number; y: number; z: number }
): [number, number, number, number] {
  const p0 = coordOf(ids[0]);
  const p1 = coordOf(ids[1]);
  const p2 = coordOf(ids[2]);
  const p3 = coordOf(ids[3]);
  const ax = p1.x - p0.x, ay = p1.y - p0.y, az = p1.z - p0.z;
  const bx = p2.x - p0.x, by = p2.y - p0.y, bz = p2.z - p0.z;
  const cx = p3.x - p0.x, cy = p3.y - p0.y, cz = p3.z - p0.z;
  const crossX = ay * bz - az * by;
  const crossY = az * bx - ax * bz;
  const crossZ = ax * by - ay * bx;
  const signedVolume = crossX * cx + crossY * cy + crossZ * cz;
  return signedVolume < 0 ? [ids[0], ids[1], ids[3], ids[2]] : ids;
}

/** Lexicographic sort key over an id tuple, zero-padded so numeric order and
 * string order agree (plain `.join()` would sort "10" before "9"). */
function canonicalCellKey(ids: readonly number[]): string {
  return ids.map((id) => id.toString().padStart(12, "0")).join("_");
}

/** Assigns dense output ids starting at `startId`, in ascending
 * {@link canonicalCellKey} order — the "deterministic regardless of input
 * order" half of {@link writeMdpa}'s contract. */
function assignIds(
  cells: readonly (readonly number[])[],
  startId: number
): { orderedOriginalIndices: number[]; idOf: Map<number, number> } {
  const withIndex = cells.map((ids, originalIndex) => ({ originalIndex, ids }));
  withIndex.sort((a, b) => {
    const ka = canonicalCellKey(a.ids);
    const kb = canonicalCellKey(b.ids);
    return ka < kb ? -1 : ka > kb ? 1 : 0;
  });
  const idOf = new Map<number, number>();
  const orderedOriginalIndices = withIndex.map((c, i) => {
    idOf.set(c.originalIndex, startId + i);
    return c.originalIndex;
  });
  return { orderedOriginalIndices, idOf };
}

/** Scientific notation, full round-trip precision (no fixed digit count —
 * `toExponential()` with no argument emits exactly as many digits as needed
 * to uniquely represent the double, same fidelity as the default `toString()`
 * this used to use, just always in `<mantissa>e±<exp>` form). */
function formatCoord(v: number): string {
  return v.toExponential();
}

function writeNodesBlock(sortedNodes: MdpaNode[]): string[] {
  const out = ["Begin Nodes"];
  sortedNodes.forEach((n, i) => out.push(`${i + 1} ${formatCoord(n.x)} ${formatCoord(n.y)} ${formatCoord(n.z)}`));
  out.push("End Nodes");
  return out;
}

/** Writes one `Begin <blockKeyword> <name> ... End <blockKeyword>` block —
 * shared by Elements/Conditions (`withPropertyId`, always property `0`) and
 * Geometries (`!withPropertyId`, id directly followed by connectivity). */
function writeCellBlock(
  blockKeyword: "Elements" | "Conditions" | "Geometries",
  name: string,
  assign: { orderedOriginalIndices: number[]; idOf: Map<number, number> },
  cells: readonly (readonly number[])[],
  withPropertyId: boolean
): string[] {
  const out = [`Begin ${blockKeyword} ${name}`];
  for (const originalIndex of assign.orderedOriginalIndices) {
    const id = assign.idOf.get(originalIndex)!;
    const conn = cells[originalIndex].join(" ");
    out.push(withPropertyId ? `${id} 0 ${conn}` : `${id} ${conn}`);
  }
  out.push(`End ${blockKeyword}`);
  return out;
}

function writeSubModelPartBlock(
  group: MdpaGroup,
  mode: MdpaMode,
  nodeIdOf: Map<number, number>,
  tetIds: ReadonlyArray<readonly number[]>,
  triIds: ReadonlyArray<readonly number[]>,
  tetIdOf: Map<number, number>,
  triIdOf: Map<number, number>,
  usedNames: Set<string>
): string[] {
  const name = sanitizeSubModelPartName(group.name, usedNames);
  const out = [`Begin SubModelPart ${name}`];

  const elementIds = group.tetIndices.map((i) => tetIdOf.get(i)!).sort((a, b) => a - b);
  const conditionIds = group.triangleIndices.map((i) => triIdOf.get(i)!).sort((a, b) => a - b);

  // Node-consistency rule: every node used by a grouped element/condition/
  // geometry must also appear in this SubModelPart's own SubModelPartNodes —
  // computed as (explicitly-selected nodes) ∪ (nodes of all grouped cells).
  const nodeIdSet = new Set<number>();
  for (const tag of group.extraNodeTags) {
    const id = nodeIdOf.get(tag);
    if (id !== undefined) nodeIdSet.add(id);
  }
  for (const i of group.tetIndices) for (const id of tetIds[i]) nodeIdSet.add(id);
  for (const i of group.triangleIndices) for (const id of triIds[i]) nodeIdSet.add(id);
  const nodeIds = [...nodeIdSet].sort((a, b) => a - b);

  out.push("    Begin SubModelPartNodes");
  for (const id of nodeIds) out.push(`    ${id}`);
  out.push("    End SubModelPartNodes");

  if (mode === "elements") {
    out.push("    Begin SubModelPartElements");
    for (const id of elementIds) out.push(`    ${id}`);
    out.push("    End SubModelPartElements");

    out.push("    Begin SubModelPartConditions");
    for (const id of conditionIds) out.push(`    ${id}`);
    out.push("    End SubModelPartConditions");
  } else {
    // Tetrahedra3D4 and Triangle3D3 share one Geometries id space (see
    // writeMdpa's doc comment), so a group's geometry ids are just their union.
    const geometryIds = [...elementIds, ...conditionIds].sort((a, b) => a - b);
    out.push("    Begin SubModelPartGeometries");
    for (const id of geometryIds) out.push(`    ${id}`);
    out.push("    End SubModelPartGeometries");
  }

  out.push("End SubModelPart");
  return out;
}

/** Replaces anything but `[A-Za-z0-9_]` with `_` (the documented MDPA-safe
 * replacement rule — no spaces/newlines in a SubModelPart name), prefixes a
 * name that doesn't start with a letter/underscore (e.g. all-digits or
 * empty) with `Part_`, and guarantees uniqueness among siblings via a `_2`,
 * `_3`, … numeric suffix — `used` accumulates across calls so later groups
 * in the same {@link writeMdpa} run see earlier ones' final names. */
function sanitizeSubModelPartName(name: string, used: Set<string>): string {
  let base = name.replace(/[^A-Za-z0-9_]/g, "_");
  if (base === "" || !/^[A-Za-z_]/.test(base)) base = `Part_${base}`;

  let candidate = base;
  let suffix = 2;
  while (used.has(candidate)) {
    candidate = `${base}_${suffix}`;
    suffix++;
  }
  used.add(candidate);
  return candidate;
}
