import { describe, it, expect } from "vitest";
import { writeMdpa, type MdpaMesh, type MdpaNode, type MdpaCell, type MdpaGroup } from "./mdpaWriter";

/**
 * A two-tet, shared-face bipyramid (A,B,C base; D/E apexes above/below) plus
 * two boundary triangles, with deliberately non-contiguous/non-1-based node
 * tags so tests can distinguish "source tag" from "assigned output id".
 * Output node ids (sorted by tag ascending): A=1 B=2 C=3 D=4 E=5.
 *
 * tet0 = [A,B,C,D] is already positive-volume (no orient swap expected).
 * tet1 = [A,B,C,E] is negative-volume as given (orientCell swaps to [A,B,E,C],
 * i.e. output ids [1,2,3,5] -> [1,2,5,3]).
 */
function baseFixture(): { nodes: MdpaNode[]; volumeCells: MdpaCell[]; surfaceCells: MdpaCell[] } {
  const nodes: MdpaNode[] = [
    { tag: 10, x: 0, y: 0, z: 0 }, // A
    { tag: 20, x: 1, y: 0, z: 0 }, // B
    { tag: 30, x: 0, y: 1, z: 0 }, // C
    { tag: 40, x: 0, y: 0, z: 1 }, // D
    { tag: 50, x: 0, y: 0, z: -1 }, // E
  ];
  const volumeCells: MdpaCell[] = [
    { kind: "tet4", nodeTags: [10, 20, 30, 40] }, // A,B,C,D
    { kind: "tet4", nodeTags: [10, 20, 30, 50] }, // A,B,C,E
  ];
  const surfaceCells: MdpaCell[] = [
    { kind: "tri3", nodeTags: [10, 20, 40] }, // A,B,D
    { kind: "tri3", nodeTags: [10, 30, 50] }, // A,C,E
  ];
  return { nodes, volumeCells, surfaceCells };
}

function mesh(overrides: Partial<MdpaMesh> = {}): MdpaMesh {
  const f = baseFixture();
  return { nodes: f.nodes, volumeCells: f.volumeCells, surfaceCells: f.surfaceCells, groups: [], ...overrides };
}

function extractBlock(text: string, beginLine: string, endLine: string): string[] {
  const lines = text.split("\n").map((l) => l.trim());
  const start = lines.indexOf(beginLine);
  const end = lines.indexOf(endLine, start);
  expect(start, `expected to find "${beginLine}"`).toBeGreaterThanOrEqual(0);
  expect(end, `expected to find "${endLine}" after "${beginLine}"`).toBeGreaterThan(start);
  return lines.slice(start + 1, end).filter((l) => l.length > 0);
}

describe("writeMdpa — Mode A (Elements + Conditions)", () => {
  it("emits exact block structure, node renumbering, and connectivity", () => {
    const text = writeMdpa(mesh(), "elements");

    expect(text).toContain("// File generated by CAD-Preview — Kratos MDPA export");
    expect(extractBlock(text, "Begin Properties 0", "End Properties")).toEqual([]);
    expect(extractBlock(text, "Begin Nodes", "End Nodes")).toEqual([
      "1 0e+0 0e+0 0e+0",
      "2 1e+0 0e+0 0e+0",
      "3 0e+0 1e+0 0e+0",
      "4 0e+0 0e+0 1e+0",
      "5 0e+0 0e+0 -1e+0",
    ]);
    expect(extractBlock(text, "Begin Elements Element3D4N", "End Elements")).toEqual(["1 0 1 2 3 4", "2 0 1 2 5 3"]);
    expect(extractBlock(text, "Begin Conditions SurfaceCondition3D3N", "End Conditions")).toEqual(["1 0 1 2 4", "2 0 1 3 5"]);
    expect(text).not.toContain("Begin SubModelPart ");
  });
});

describe("writeMdpa — Mode B (Geometries)", () => {
  it("shares one id space across Tetrahedra3D4/Triangle3D3 and omits property ids", () => {
    const text = writeMdpa(mesh(), "geometries");
    expect(text).not.toContain("Begin Properties");
    expect(extractBlock(text, "Begin Geometries Tetrahedra3D4", "End Geometries")).toEqual(["1 1 2 3 4", "2 1 2 5 3"]);
    // Triangle3D3 continues the shared id counter (3, 4) rather than restarting.
    const lines = text.split("\n");
    const triStart = lines.indexOf("Begin Geometries Triangle3D3");
    const triEnd = lines.indexOf("End Geometries", triStart);
    const triLines = lines.slice(triStart + 1, triEnd).map((l) => l.trim()).filter(Boolean);
    expect(triLines).toEqual(["3 1 2 4", "4 1 3 5"]);
  });
});

describe("writeMdpa — cell orientation", () => {
  it("leaves an already-positive-volume tet unchanged", () => {
    const text = writeMdpa(mesh({ volumeCells: [{ kind: "tet4", nodeTags: [10, 20, 30, 40] }], surfaceCells: [] }), "elements");
    expect(extractBlock(text, "Begin Elements Element3D4N", "End Elements")).toEqual(["1 0 1 2 3 4"]);
  });

  it("swaps the last two ids of a negative-volume tet", () => {
    const text = writeMdpa(mesh({ volumeCells: [{ kind: "tet4", nodeTags: [10, 20, 30, 50] }], surfaceCells: [] }), "elements");
    expect(extractBlock(text, "Begin Elements Element3D4N", "End Elements")).toEqual(["1 0 1 2 5 3"]);
  });

  it("warns (but does not reorder) an inverted hex, and reorders none for a positive hex", () => {
    // Unit cube, gmsh/Kratos hex8 corner order (bottom z=0 CCW, top z=1 CCW).
    const cube: MdpaNode[] = [
      { tag: 1, x: 0, y: 0, z: 0 }, { tag: 2, x: 1, y: 0, z: 0 }, { tag: 3, x: 1, y: 1, z: 0 }, { tag: 4, x: 0, y: 1, z: 0 },
      { tag: 5, x: 0, y: 0, z: 1 }, { tag: 6, x: 1, y: 0, z: 1 }, { tag: 7, x: 1, y: 1, z: 1 }, { tag: 8, x: 0, y: 1, z: 1 },
    ];
    const positive: MdpaCell = { kind: "hex8", nodeTags: [1, 2, 3, 4, 5, 6, 7, 8] };
    const warnings: string[] = [];
    writeMdpa({ nodes: cube, volumeCells: [positive], surfaceCells: [], groups: [] }, "elements", (m) => warnings.push(m));
    expect(warnings).toEqual([]);

    // Invert by swapping the top/bottom faces (negative signed volume).
    const inverted: MdpaCell = { kind: "hex8", nodeTags: [5, 6, 7, 8, 1, 2, 3, 4] };
    const warnings2: string[] = [];
    const text = writeMdpa({ nodes: cube, volumeCells: [inverted], surfaceCells: [], groups: [] }, "elements", (m) => warnings2.push(m));
    expect(warnings2.length).toBe(1);
    expect(warnings2[0]).toContain("hex8");
    // Emitted unchanged (ids 5,6,7,8,1,2,3,4).
    expect(extractBlock(text, "Begin Elements Element3D8N", "End Elements")).toEqual(["1 0 5 6 7 8 1 2 3 4"]);
  });
});

describe("writeMdpa — new cell kinds", () => {
  const cube: MdpaNode[] = [
    { tag: 1, x: 0, y: 0, z: 0 }, { tag: 2, x: 1, y: 0, z: 0 }, { tag: 3, x: 1, y: 1, z: 0 }, { tag: 4, x: 0, y: 1, z: 0 },
    { tag: 5, x: 0, y: 0, z: 1 }, { tag: 6, x: 1, y: 0, z: 1 }, { tag: 7, x: 1, y: 1, z: 1 }, { tag: 8, x: 0, y: 1, z: 1 },
  ];

  it("writes Hexahedra3D8 / Quadrilateral3D4 with the right block names in both modes", () => {
    const m: MdpaMesh = {
      nodes: cube,
      volumeCells: [{ kind: "hex8", nodeTags: [1, 2, 3, 4, 5, 6, 7, 8] }],
      surfaceCells: [{ kind: "quad4", nodeTags: [1, 2, 3, 4] }],
      groups: [],
    };
    const els = writeMdpa(m, "elements");
    expect(els).toContain("Begin Elements Element3D8N");
    expect(els).toContain("Begin Conditions SurfaceCondition3D4N");
    const geo = writeMdpa(m, "geometries");
    expect(geo).toContain("Begin Geometries Hexahedra3D8");
    expect(geo).toContain("Begin Geometries Quadrilateral3D4");
  });

  it("writes quadratic tet10 / tri6 / hex27 / quad9 geometry blocks", () => {
    const tet10: MdpaCell = { kind: "tet10", nodeTags: [10, 20, 30, 40, 11, 12, 13, 14, 15, 16] };
    const tri6: MdpaCell = { kind: "tri6", nodeTags: [10, 20, 30, 11, 12, 13] };
    const text = writeMdpa(
      { nodes: baseFixture().nodes.concat([6, 7, 8, 9, 11, 12, 13, 14, 15, 16].map((t) => ({ tag: t, x: 0.5, y: 0.5, z: 0 }))), volumeCells: [tet10], surfaceCells: [tri6], groups: [] },
      "geometries"
    );
    expect(text).toContain("Begin Geometries Tetrahedra3D10");
    expect(text).toContain("Begin Geometries Triangle3D6");
    // tet10 line has 10 connectivity nodes after the id
    const tetLine = extractBlock(text, "Begin Geometries Tetrahedra3D10", "End Geometries")[0];
    expect(tetLine.split(/\s+/).length).toBe(1 + 10);
  });

  it("continues element ids across kind blocks but restarts conditions at 1", () => {
    const m: MdpaMesh = {
      nodes: cube,
      volumeCells: [
        { kind: "tet4", nodeTags: [1, 2, 3, 5] },
        { kind: "hex8", nodeTags: [1, 2, 3, 4, 5, 6, 7, 8] },
      ],
      surfaceCells: [{ kind: "quad4", nodeTags: [1, 2, 3, 4] }],
      groups: [],
    };
    const text = writeMdpa(m, "elements");
    // tet4 gets element id 1, hex8 continues at id 2 (one continuous Element space).
    expect(extractBlock(text, "Begin Elements Element3D4N", "End Elements")[0]).toMatch(/^1 0 /);
    expect(extractBlock(text, "Begin Elements Element3D8N", "End Elements")[0]).toMatch(/^2 0 /);
    // Conditions start their own space at 1.
    expect(extractBlock(text, "Begin Conditions SurfaceCondition3D4N", "End Conditions")[0]).toMatch(/^1 0 /);
  });
});

describe("writeMdpa — empty-block omission", () => {
  it("omits Elements when there are no volume cells", () => {
    const text = writeMdpa(mesh({ volumeCells: [] }), "elements");
    expect(text).not.toContain("Begin Elements");
    expect(text).toContain("Begin Conditions SurfaceCondition3D3N");
  });

  it("omits Conditions when there are no surface cells", () => {
    const text = writeMdpa(mesh({ surfaceCells: [] }), "elements");
    expect(text).not.toContain("Begin Conditions");
    expect(text).toContain("Begin Elements Element3D4N");
  });

  it("emits only Properties/Nodes when there are neither", () => {
    const text = writeMdpa(mesh({ volumeCells: [], surfaceCells: [] }), "elements");
    expect(text).toContain("Begin Properties 0");
    expect(text).toContain("Begin Nodes");
    expect(text).not.toContain("Begin Elements");
    expect(text).not.toContain("Begin Conditions");
  });
});

describe("writeMdpa — SubModelParts (flat groups)", () => {
  it("emits one flat SubModelPart per group with correct element/condition/node sets", () => {
    const groups: MdpaGroup[] = [
      { name: "Solid", volumeCellIndices: [0], surfaceCellIndices: [], extraNodeTags: [] },
      { name: "Outlet", volumeCellIndices: [], surfaceCellIndices: [1], extraNodeTags: [40] /* D, not on tri1 */ },
    ];
    const text = writeMdpa(mesh({ groups }), "elements");

    const lines = text.split("\n");
    const solidStart = lines.indexOf("Begin SubModelPart Solid");
    const solidEnd = lines.indexOf("End SubModelPart", solidStart);
    const solidBody = lines.slice(solidStart, solidEnd + 1).join("\n");
    expect(extractBlock(solidBody, "Begin SubModelPartNodes", "End SubModelPartNodes")).toEqual(["1", "2", "3", "4"]);
    expect(extractBlock(solidBody, "Begin SubModelPartElements", "End SubModelPartElements")).toEqual(["1"]);
    expect(extractBlock(solidBody, "Begin SubModelPartConditions", "End SubModelPartConditions")).toEqual([]);

    const outletStart = lines.indexOf("Begin SubModelPart Outlet", solidEnd);
    const outletEnd = lines.indexOf("End SubModelPart", outletStart);
    const outletBody = lines.slice(outletStart, outletEnd + 1).join("\n");
    // tri1 = A,C,E -> ids 1,3,5 ; plus extra D (id 4).
    expect(extractBlock(outletBody, "Begin SubModelPartNodes", "End SubModelPartNodes")).toEqual(["1", "3", "4", "5"]);
    expect(extractBlock(outletBody, "Begin SubModelPartElements", "End SubModelPartElements")).toEqual([]);
    expect(extractBlock(outletBody, "Begin SubModelPartConditions", "End SubModelPartConditions")).toEqual(["2"]);

    expect(solidBody.slice("Begin SubModelPart Solid".length)).not.toContain("Begin SubModelPart ");
  });

  it("uses SubModelPartGeometries (shared id space) in Mode B", () => {
    const groups: MdpaGroup[] = [{ name: "Solid", volumeCellIndices: [0, 1], surfaceCellIndices: [0], extraNodeTags: [] }];
    const text = writeMdpa(mesh({ groups }), "geometries");
    expect(text).not.toContain("Begin SubModelPartElements");
    const geomIds = extractBlock(text, "Begin SubModelPartGeometries", "End SubModelPartGeometries");
    expect(geomIds).toEqual(["1", "2", "3"]); // tet0=1, tet1=2, tri0=3
  });
});

describe("writeMdpa — SubModelPart name sanitization and uniqueness", () => {
  it("sanitizes invalid characters and disambiguates collisions", () => {
    const groups: MdpaGroup[] = [
      { name: "My Part!", volumeCellIndices: [], surfaceCellIndices: [], extraNodeTags: [] },
      { name: "My_Part_", volumeCellIndices: [], surfaceCellIndices: [], extraNodeTags: [] },
      { name: "   ", volumeCellIndices: [], surfaceCellIndices: [], extraNodeTags: [] },
    ];
    const text = writeMdpa(mesh({ volumeCells: [], surfaceCells: [], groups }), "elements");
    expect(text).toContain("Begin SubModelPart My_Part_\n");
    expect(text).toContain("Begin SubModelPart My_Part__2\n");
    const names = [...text.matchAll(/^Begin SubModelPart (\S+)$/gm)].map((m) => m[1]);
    expect(names).toHaveLength(3);
    expect(new Set(names).size).toBe(3);
  });
});

describe("writeMdpa — determinism", () => {
  it("produces byte-identical output regardless of input array order, across kinds", () => {
    const groups: MdpaGroup[] = [
      { name: "Solid", volumeCellIndices: [0], surfaceCellIndices: [], extraNodeTags: [] },
      { name: "Outlet", volumeCellIndices: [], surfaceCellIndices: [1], extraNodeTags: [] },
    ];
    const f = baseFixture();
    const textA = writeMdpa({ ...f, groups }, "elements");

    const meshB: MdpaMesh = {
      nodes: [...f.nodes].reverse(),
      volumeCells: [f.volumeCells[1], f.volumeCells[0]],
      surfaceCells: [f.surfaceCells[1], f.surfaceCells[0]],
      groups: [
        { name: "Solid", volumeCellIndices: [1], surfaceCellIndices: [], extraNodeTags: [] },
        { name: "Outlet", volumeCellIndices: [], surfaceCellIndices: [0], extraNodeTags: [] },
      ],
    };
    expect(writeMdpa(meshB, "elements")).toBe(textA);
  });
});
