import { describe, it, expect } from "vitest";
import { writeMdpa, type MdpaMesh, type MdpaNode, type MdpaTet, type MdpaTriangle, type MdpaGroup } from "./mdpaWriter";

/**
 * A two-tet, shared-face bipyramid (A,B,C base; D/E apexes above/below) plus
 * two boundary triangles, with deliberately non-contiguous/non-1-based node
 * tags so tests can distinguish "source tag" from "assigned output id".
 * Output node ids (sorted by tag ascending): A=1 B=2 C=3 D=4 E=5.
 *
 * tet0 = [A,B,C,D] is already positive-volume (no orientTet swap expected).
 * tet1 = [A,B,C,E] is negative-volume as given (orientTet swaps the last two
 * ids: [A,B,C,E] -> [A,B,E,C], i.e. output ids [1,2,3,5] -> [1,2,5,3]).
 */
function baseFixture(): { nodes: MdpaNode[]; tets: MdpaTet[]; triangles: MdpaTriangle[] } {
  const nodes: MdpaNode[] = [
    { tag: 10, x: 0, y: 0, z: 0 }, // A
    { tag: 20, x: 1, y: 0, z: 0 }, // B
    { tag: 30, x: 0, y: 1, z: 0 }, // C
    { tag: 40, x: 0, y: 0, z: 1 }, // D
    { tag: 50, x: 0, y: 0, z: -1 }, // E
  ];
  const tets: MdpaTet[] = [
    { nodeTags: [10, 20, 30, 40] }, // A,B,C,D
    { nodeTags: [10, 20, 30, 50] }, // A,B,C,E
  ];
  const triangles: MdpaTriangle[] = [
    { nodeTags: [10, 20, 40] }, // A,B,D
    { nodeTags: [10, 30, 50] }, // A,C,E
  ];
  return { nodes, tets, triangles };
}

function extractBlock(text: string, beginLine: string, endLine: string): string[] {
  const lines = text.split("\n").map((l) => l.trim());
  const start = lines.indexOf(beginLine);
  const end = lines.indexOf(endLine, start);
  expect(start, `expected to find "${beginLine}"`).toBeGreaterThanOrEqual(0);
  expect(end, `expected to find "${endLine}" after "${beginLine}"`).toBeGreaterThan(start);
  return lines.slice(start + 1, end).filter((l) => l.length > 0);
}

describe("writeMdpa — Mode A (Elements + Conditions)", () => {
  it("emits exact block structure, node renumbering, and connectivity", () => {
    const { nodes, tets, triangles } = baseFixture();
    const mesh: MdpaMesh = { nodes, tets, triangles, groups: [] };
    const text = writeMdpa(mesh, "elements");

    expect(text).toContain("// File generated by CAD-Preview — Kratos MDPA export");

    const properties = extractBlock(text, "Begin Properties 0", "End Properties");
    expect(properties).toEqual([]);

    const nodeLines = extractBlock(text, "Begin Nodes", "End Nodes");
    expect(nodeLines).toEqual([
      "1 0e+0 0e+0 0e+0",
      "2 1e+0 0e+0 0e+0",
      "3 0e+0 1e+0 0e+0",
      "4 0e+0 0e+0 1e+0",
      "5 0e+0 0e+0 -1e+0",
    ]);

    const elementLines = extractBlock(text, "Begin Elements Element3D4N", "End Elements");
    expect(elementLines).toEqual(["1 0 1 2 3 4", "2 0 1 2 5 3"]);

    const conditionLines = extractBlock(text, "Begin Conditions SurfaceCondition3D3N", "End Conditions");
    expect(conditionLines).toEqual(["1 0 1 2 4", "2 0 1 3 5"]);

    expect(text).not.toContain("Begin SubModelPart ");
  });
});

describe("writeMdpa — Mode B (Geometries)", () => {
  it("shares one id space across Tetrahedra3D4/Triangle3D3 and omits property ids", () => {
    const { nodes, tets, triangles } = baseFixture();
    const mesh: MdpaMesh = { nodes, tets, triangles, groups: [] };
    const text = writeMdpa(mesh, "geometries");

    expect(text).not.toContain("Begin Properties");

    const tetLines = extractBlock(text, "Begin Geometries Tetrahedra3D4", "End Geometries");
    expect(tetLines).toEqual(["1 1 2 3 4", "2 1 2 5 3"]);

    // Triangle3D3 continues the id counter (3, 4) rather than restarting at 1 —
    // both geometry kinds live in Kratos's single Geometries container.
    const lines = text.split("\n");
    const triStart = lines.indexOf("Begin Geometries Triangle3D3");
    const triEnd = lines.indexOf("End Geometries", triStart);
    const triLines = lines
      .slice(triStart + 1, triEnd)
      .map((l) => l.trim())
      .filter(Boolean);
    expect(triLines).toEqual(["3 1 2 4", "4 1 3 5"]);
  });
});

describe("writeMdpa — tet orientation", () => {
  it("leaves an already-positive-volume tet's node order unchanged", () => {
    const mesh: MdpaMesh = {
      nodes: baseFixture().nodes,
      tets: [{ nodeTags: [10, 20, 30, 40] }], // tet0 — positive as given
      triangles: [],
      groups: [],
    };
    const text = writeMdpa(mesh, "elements");
    const elementLines = extractBlock(text, "Begin Elements Element3D4N", "End Elements");
    expect(elementLines).toEqual(["1 0 1 2 3 4"]);
  });

  it("swaps the last two ids of a negative-volume tet, yielding a positive recomputed volume", () => {
    const mesh: MdpaMesh = {
      nodes: baseFixture().nodes,
      tets: [{ nodeTags: [10, 20, 30, 50] }], // tet1 — negative as given
      triangles: [],
      groups: [],
    };
    const text = writeMdpa(mesh, "elements");
    const elementLines = extractBlock(text, "Begin Elements Element3D4N", "End Elements");
    // Output ids: A=1 B=2 C=3 E=5 — input order [1,2,3,5] must come out as [1,2,5,3].
    expect(elementLines).toEqual(["1 0 1 2 5 3"]);

    // Independently recompute the signed volume from the fixture's own coordinates
    // in the *output* order to confirm it's now positive, not just "different".
    const byTag = new Map(baseFixture().nodes.map((n) => [n.tag, n]));
    const [a, b, c, e] = [byTag.get(10)!, byTag.get(20)!, byTag.get(30)!, byTag.get(50)!];
    const outputOrder = [a, b, e, c]; // matches ids [1,2,5,3]
    const [p0, p1, p2, p3] = outputOrder;
    const ax = p1.x - p0.x, ay = p1.y - p0.y, az = p1.z - p0.z;
    const bx = p2.x - p0.x, by = p2.y - p0.y, bz = p2.z - p0.z;
    const cx = p3.x - p0.x, cy = p3.y - p0.y, cz = p3.z - p0.z;
    const cross = [ay * bz - az * by, az * bx - ax * bz, ax * by - ay * bx];
    const signedVolume = cross[0] * cx + cross[1] * cy + cross[2] * cz;
    expect(signedVolume).toBeGreaterThan(0);
  });
});

describe("writeMdpa — empty-block omission", () => {
  const { nodes, tets, triangles } = baseFixture();

  it("omits Elements/Geometries-Tetrahedra3D4 when there are no tets", () => {
    const mesh: MdpaMesh = { nodes, tets: [], triangles, groups: [] };
    const textA = writeMdpa(mesh, "elements");
    expect(textA).not.toContain("Begin Elements");
    expect(textA).toContain("Begin Conditions SurfaceCondition3D3N");

    const textB = writeMdpa(mesh, "geometries");
    expect(textB).not.toContain("Begin Geometries Tetrahedra3D4");
    expect(textB).toContain("Begin Geometries Triangle3D3");
  });

  it("omits Conditions/Geometries-Triangle3D3 when there are no triangles", () => {
    const mesh: MdpaMesh = { nodes, tets, triangles: [], groups: [] };
    const textA = writeMdpa(mesh, "elements");
    expect(textA).not.toContain("Begin Conditions");
    expect(textA).toContain("Begin Elements Element3D4N");

    const textB = writeMdpa(mesh, "geometries");
    expect(textB).not.toContain("Begin Geometries Triangle3D3");
    expect(textB).toContain("Begin Geometries Tetrahedra3D4");
  });

  it("emits only Properties/Nodes (or just Nodes) when there are neither", () => {
    const mesh: MdpaMesh = { nodes, tets: [], triangles: [], groups: [] };

    const textA = writeMdpa(mesh, "elements");
    expect(textA).toContain("Begin Properties 0");
    expect(textA).toContain("Begin Nodes");
    expect(textA).not.toContain("Begin Elements");
    expect(textA).not.toContain("Begin Conditions");

    const textB = writeMdpa(mesh, "geometries");
    expect(textB).not.toContain("Begin Properties");
    expect(textB).toContain("Begin Nodes");
    expect(textB).not.toContain("Begin Geometries");
  });
});

describe("writeMdpa — SubModelParts (flat groups)", () => {
  it("emits one flat SubModelPart per group with correct element/condition/node sets", () => {
    const { nodes, tets, triangles } = baseFixture();
    const groups: MdpaGroup[] = [
      { name: "Solid", tetIndices: [0], triangleIndices: [], extraNodeTags: [] },
      { name: "Outlet", tetIndices: [], triangleIndices: [1], extraNodeTags: [40] /* D, not on tri1 */ },
    ];
    const mesh: MdpaMesh = { nodes, tets, triangles, groups };
    const text = writeMdpa(mesh, "elements");

    const lines = text.split("\n");
    const solidStart = lines.indexOf("Begin SubModelPart Solid");
    const solidEnd = lines.indexOf("End SubModelPart", solidStart);
    expect(solidStart).toBeGreaterThanOrEqual(0);
    const solidBody = lines.slice(solidStart, solidEnd + 1).join("\n");
    expect(extractBlock(solidBody, "Begin SubModelPartNodes", "End SubModelPartNodes")).toEqual(["1", "2", "3", "4"]);
    expect(extractBlock(solidBody, "Begin SubModelPartElements", "End SubModelPartElements")).toEqual(["1"]);
    expect(extractBlock(solidBody, "Begin SubModelPartConditions", "End SubModelPartConditions")).toEqual([]);

    const outletStart = lines.indexOf("Begin SubModelPart Outlet", solidEnd);
    const outletEnd = lines.indexOf("End SubModelPart", outletStart);
    expect(outletStart).toBeGreaterThan(solidEnd);
    const outletBody = lines.slice(outletStart, outletEnd + 1).join("\n");
    // tri1 = A,C,E -> ids 1,3,5 ; plus extraNodeTags' D (id 4) not otherwise referenced.
    expect(extractBlock(outletBody, "Begin SubModelPartNodes", "End SubModelPartNodes")).toEqual(["1", "3", "4", "5"]);
    expect(extractBlock(outletBody, "Begin SubModelPartElements", "End SubModelPartElements")).toEqual([]);
    expect(extractBlock(outletBody, "Begin SubModelPartConditions", "End SubModelPartConditions")).toEqual(["2"]);

    // Flatness: no group's body contains a nested SubModelPart. (Trailing space
    // matters — "Begin SubModelPart" alone is also a prefix of "Begin
    // SubModelPartNodes"/"...Elements"/"...Conditions", which are expected.)
    expect(solidBody.slice("Begin SubModelPart Solid".length)).not.toContain("Begin SubModelPart ");
    expect(outletBody.slice("Begin SubModelPart Outlet".length)).not.toContain("Begin SubModelPart ");
  });

  it("uses SubModelPartGeometries (not Elements/Conditions) in Mode B", () => {
    const { nodes, tets, triangles } = baseFixture();
    const groups: MdpaGroup[] = [{ name: "Solid", tetIndices: [0, 1], triangleIndices: [0], extraNodeTags: [] }];
    const mesh: MdpaMesh = { nodes, tets, triangles, groups };
    const text = writeMdpa(mesh, "geometries");

    expect(text).not.toContain("Begin SubModelPartElements");
    expect(text).not.toContain("Begin SubModelPartConditions");
    const geomIds = extractBlock(text, "Begin SubModelPartGeometries", "End SubModelPartGeometries");
    // tet0=1, tet1=2, tri0=3 (Geometries share one id space) -> sorted ascending.
    expect(geomIds).toEqual(["1", "2", "3"]);
  });
});

describe("writeMdpa — SubModelPart name sanitization and uniqueness", () => {
  it("sanitizes invalid characters and disambiguates collisions", () => {
    const { nodes } = baseFixture();
    const groups: MdpaGroup[] = [
      { name: "My Part!", tetIndices: [], triangleIndices: [], extraNodeTags: [] },
      { name: "My_Part_", tetIndices: [], triangleIndices: [], extraNodeTags: [] },
      { name: "   ", tetIndices: [], triangleIndices: [], extraNodeTags: [] },
    ];
    const mesh: MdpaMesh = { nodes, tets: [], triangles: [], groups };
    const text = writeMdpa(mesh, "elements");

    expect(text).toContain("Begin SubModelPart My_Part_\n");
    expect(text).toContain("Begin SubModelPart My_Part__2\n");
    // The third (whitespace-only) name must still produce a distinct, valid,
    // non-empty block header rather than colliding or crashing.
    const names = [...text.matchAll(/^Begin SubModelPart (\S+)$/gm)].map((m) => m[1]);
    expect(names).toHaveLength(3);
    expect(new Set(names).size).toBe(3);
  });
});

describe("writeMdpa — determinism", () => {
  it("produces byte-identical, ascending-id output regardless of input array order", () => {
    const fixture = baseFixture();
    const groups: MdpaGroup[] = [
      { name: "Solid", tetIndices: [0], triangleIndices: [], extraNodeTags: [] },
      { name: "Outlet", tetIndices: [], triangleIndices: [1], extraNodeTags: [] },
    ];

    const meshA: MdpaMesh = { ...fixture, groups };
    const textA = writeMdpa(meshA, "elements");

    // Shuffle every array's order; groups reference cells by (now-different)
    // index, so remap the indices to point at the same logical cells.
    const shuffledTets = [fixture.tets[1], fixture.tets[0]];
    const shuffledTriangles = [fixture.triangles[1], fixture.triangles[0]];
    const shuffledGroups: MdpaGroup[] = [
      { name: "Solid", tetIndices: [1] /* was 0, now at index 1 */, triangleIndices: [], extraNodeTags: [] },
      { name: "Outlet", tetIndices: [], triangleIndices: [0] /* was 1, now at index 0 */, extraNodeTags: [] },
    ];
    const meshB: MdpaMesh = {
      nodes: [...fixture.nodes].reverse(),
      tets: shuffledTets,
      triangles: shuffledTriangles,
      groups: shuffledGroups,
    };
    const textB = writeMdpa(meshB, "elements");

    expect(textB).toBe(textA);
  });
});
