/**
 * Hand-written Kratos MDPA (`.mdpa`) ASCII serializer. Pure and vscode/WASM-free
 * so it unit-tests headless, mirroring `partsSidecar.ts`/`editOps.ts`/
 * `meshOptionsSidecar.ts`'s "pure logic module" convention — the WASM-dependent
 * extraction of `MdpaMesh` from a live gmsh model lives in `gmshService.ts`.
 *
 * MDPA has no off-the-shelf writer in any of this project's dependencies (unlike
 * every other mesh export format, which routes through Gmsh's own `gmsh.write()`)
 * — see `doc/gmsh-integration.md`'s "Kratos MDPA" section for the full spec
 * citations (block syntax, node ordering) this module was built against.
 *
 * Handles the full cell catalogue of {@link MdpaCellKind} — linear and quadratic
 * tetrahedra, hexahedra, prisms, pyramids (volume) and triangles, quadrilaterals
 * (surface) — via the shared `gmshElementTypes.ts` table, which supplies each
 * kind's Kratos block names and node counts. Callers must pass cells whose
 * `nodeTags` are already in **Kratos node order** (`gmshService.ts` applies the
 * gmsh→Kratos permutation during extraction).
 */

import {
  MDPA_KIND_INFO,
  VOLUME_KIND_ORDER,
  SURFACE_KIND_ORDER,
  signedVolume,
  type MdpaCellKind,
} from "./gmshElementTypes";

export type MdpaMode = "elements" | "geometries";

export interface MdpaNode {
  /** Opaque source id (e.g. a gmsh node tag) — need not be 1-based or contiguous. */
  tag: number;
  x: number;
  y: number;
  z: number;
}

/** One finite element / condition / geometry. `nodeTags` are source node tags in
 *  **Kratos** node order (length must equal `MDPA_KIND_INFO[kind].numNodes`). */
export interface MdpaCell {
  kind: MdpaCellKind;
  nodeTags: number[];
}

/** One named region (from a CAD-Preview `Part`) to emit as a Kratos SubModelPart. */
export interface MdpaGroup {
  name: string;
  /** Indices into {@link MdpaMesh.volumeCells}. */
  volumeCellIndices: number[];
  /** Indices into {@link MdpaMesh.surfaceCells}. */
  surfaceCellIndices: number[];
  /** Node tags from the part's own point/curve selections, beyond what its
   * cells already reference — see the node-consistency rule below. */
  extraNodeTags: number[];
}

export interface MdpaMesh {
  nodes: MdpaNode[];
  /** 3D cells → `Elements` (elements mode) or volume `Geometries` (geometries mode). */
  volumeCells: MdpaCell[];
  /** 2D cells → `Conditions` (elements mode) or surface `Geometries` (geometries mode). */
  surfaceCells: MdpaCell[];
  /** Flat — this codebase's `Part[]` has no nesting concept. */
  groups: MdpaGroup[];
}

interface Coord {
  x: number;
  y: number;
  z: number;
}

/**
 * Serializes `mesh` to MDPA ASCII text. `"elements"` writes one `Element*`
 * block per volume kind (each cell carrying a `prop_id`, always `0` — this
 * codebase has no material/property data) under a `Begin Properties 0` block,
 * plus one `Condition*` block per surface kind; `"geometries"` writes
 * `Geometries` blocks instead (no property id) which, per Kratos's single
 * `Geometries` container, **share one id space** across every kind.
 *
 * Deterministic: node ids by source `tag` ascending; cell ids by each cell's
 * own (renumbered) node-id tuple ascending within a kind, kinds emitted in the
 * fixed {@link VOLUME_KIND_ORDER}/{@link SURFACE_KIND_ORDER} — so output is
 * byte-identical for the same mesh regardless of the generator's internal (not
 * contractually ordered) enumeration. An empty kind omits its block entirely.
 *
 * `onWarning` (optional) receives a message when a non-tetrahedral cell is found
 * with a negative signed volume — such cells are emitted unchanged (there is no
 * simple safe re-ordering for a hex/prism/pyramid); tetrahedra are silently
 * re-oriented instead.
 */
export function writeMdpa(mesh: MdpaMesh, mode: MdpaMode, onWarning?: (msg: string) => void): string {
  const { nodeIdOf, sortedNodes } = buildNodeIdMap(mesh.nodes);
  const coordOf = (id: number): Coord => sortedNodes[id - 1];

  // Resolve every cell to Kratos-ordered, oriented output node ids.
  const volumeResolved = mesh.volumeCells.map((c) =>
    orientCell(c.kind, c.nodeTags.map((tag) => nodeIdOf.get(tag)!), coordOf, onWarning)
  );
  const surfaceResolved = mesh.surfaceCells.map((c) => c.nodeTags.map((tag) => nodeIdOf.get(tag)!));

  // Assign ids. Elements/Conditions have separate id spaces; Geometries share one.
  const volumes = assignBlocks(
    mesh.volumeCells.map((c, i) => ({ kind: c.kind, ids: volumeResolved[i], originalIndex: i })),
    VOLUME_KIND_ORDER,
    1
  );
  const surfaceStart = mode === "geometries" ? volumes.nextId : 1;
  const surfaces = assignBlocks(
    mesh.surfaceCells.map((c, i) => ({ kind: c.kind, ids: surfaceResolved[i], originalIndex: i })),
    SURFACE_KIND_ORDER,
    surfaceStart
  );

  const lines: string[] = [
    "// File generated by CAD-Preview — Kratos MDPA export",
    mode === "elements" ? "// Mode: Elements + Conditions" : "// Mode: Geometries",
    "",
  ];
  if (mode === "elements") lines.push("Begin Properties 0", "End Properties", "");
  lines.push(...writeNodesBlock(sortedNodes), "");

  if (mode === "elements") {
    for (const block of volumes.blocks) {
      const name = MDPA_KIND_INFO[block.kind].elementName!;
      lines.push(...writeCellBlock("Elements", name, block.entries, true), "");
    }
    for (const block of surfaces.blocks) {
      const name = MDPA_KIND_INFO[block.kind].conditionName!;
      lines.push(...writeCellBlock("Conditions", name, block.entries, true), "");
    }
  } else {
    for (const block of [...volumes.blocks, ...surfaces.blocks]) {
      const name = MDPA_KIND_INFO[block.kind].geometryName;
      lines.push(...writeCellBlock("Geometries", name, block.entries, false), "");
    }
  }

  const usedNames = new Set<string>();
  for (const group of mesh.groups) {
    lines.push(
      ...writeSubModelPartBlock(group, mode, nodeIdOf, volumeResolved, surfaceResolved, volumes.idOf, surfaces.idOf, usedNames)
    );
  }

  return lines.join("\n").trimEnd() + "\n";
}

/** Sorts by source tag ascending and assigns dense 1-based output ids. */
function buildNodeIdMap(nodes: MdpaNode[]): { nodeIdOf: Map<number, number>; sortedNodes: MdpaNode[] } {
  const sortedNodes = [...nodes].sort((a, b) => a.tag - b.tag);
  const nodeIdOf = new Map<number, number>();
  sortedNodes.forEach((n, i) => nodeIdOf.set(n.tag, i + 1));
  return { nodeIdOf, sortedNodes };
}

const TET4_FLIP = [0, 1, 3, 2];
const TET10_FLIP = [0, 1, 3, 2, 4, 8, 7, 6, 5, 9];

/**
 * Ensures a cell has a positive Jacobian. Tetrahedra with a negative signed
 * volume are re-oriented by the appropriate corner/mid-edge swap (`TET*_FLIP`) —
 * a well-defined correction. Other volume kinds have no simple safe flip; an
 * inverted one is emitted unchanged and `onWarning` is called. Surface cells and
 * correctly-oriented cells pass through untouched.
 */
function orientCell(
  kind: MdpaCellKind,
  ids: number[],
  coordOf: (id: number) => Coord,
  onWarning?: (msg: string) => void
): number[] {
  const info = MDPA_KIND_INFO[kind];
  const corners = ids.slice(0, info.numCorners).map(coordOf);
  const vol = signedVolume(kind, corners);
  if (vol >= 0) return ids;
  if (kind === "tet4") return TET4_FLIP.map((i) => ids[i]);
  if (kind === "tet10") return TET10_FLIP.map((i) => ids[i]);
  onWarning?.(`Emitting an inverted ${kind} cell (negative signed volume) unchanged — no safe re-orientation.`);
  return ids;
}

/** Lexicographic sort key over an id tuple, zero-padded so numeric order and
 * string order agree (plain `.join()` would sort "10" before "9"). */
function canonicalCellKey(ids: readonly number[]): string {
  return ids.map((id) => id.toString().padStart(12, "0")).join("_");
}

interface CellEntry {
  id: number;
  ids: number[];
}
interface KindBlock {
  kind: MdpaCellKind;
  entries: CellEntry[];
}

/**
 * Buckets cells by kind (in `kindOrder`), assigns dense output ids from
 * `startId` continuously across the kinds, sorting within each kind by
 * {@link canonicalCellKey} — the deterministic half of {@link writeMdpa}'s
 * contract. Returns the ordered non-empty blocks, a per-original-index id map
 * (for SubModelPart cross-referencing), and the next free id.
 */
function assignBlocks(
  cells: Array<{ kind: MdpaCellKind; ids: number[]; originalIndex: number }>,
  kindOrder: readonly MdpaCellKind[],
  startId: number
): { blocks: KindBlock[]; idOf: Map<number, number>; nextId: number } {
  const byKind = new Map<MdpaCellKind, Array<{ ids: number[]; originalIndex: number }>>();
  for (const c of cells) {
    let bucket = byKind.get(c.kind);
    if (!bucket) byKind.set(c.kind, (bucket = []));
    bucket.push({ ids: c.ids, originalIndex: c.originalIndex });
  }

  const blocks: KindBlock[] = [];
  const idOf = new Map<number, number>();
  let nextId = startId;
  for (const kind of kindOrder) {
    const bucket = byKind.get(kind);
    if (!bucket || bucket.length === 0) continue;
    bucket.sort((a, b) => {
      const ka = canonicalCellKey(a.ids);
      const kb = canonicalCellKey(b.ids);
      return ka < kb ? -1 : ka > kb ? 1 : 0;
    });
    const entries: CellEntry[] = bucket.map((c) => {
      const id = nextId++;
      idOf.set(c.originalIndex, id);
      return { id, ids: c.ids };
    });
    blocks.push({ kind, entries });
  }
  return { blocks, idOf, nextId };
}

/** Scientific notation, full round-trip precision. */
function formatCoord(v: number): string {
  return v.toExponential();
}

function writeNodesBlock(sortedNodes: MdpaNode[]): string[] {
  const out = ["Begin Nodes"];
  sortedNodes.forEach((n, i) => out.push(`${i + 1} ${formatCoord(n.x)} ${formatCoord(n.y)} ${formatCoord(n.z)}`));
  out.push("End Nodes");
  return out;
}

/** Writes one `Begin <blockKeyword> <name> ... End <blockKeyword>` block. */
function writeCellBlock(
  blockKeyword: "Elements" | "Conditions" | "Geometries",
  name: string,
  entries: CellEntry[],
  withPropertyId: boolean
): string[] {
  const out = [`Begin ${blockKeyword} ${name}`];
  for (const { id, ids } of entries) {
    const conn = ids.join(" ");
    out.push(withPropertyId ? `${id} 0 ${conn}` : `${id} ${conn}`);
  }
  out.push(`End ${blockKeyword}`);
  return out;
}

function writeSubModelPartBlock(
  group: MdpaGroup,
  mode: MdpaMode,
  nodeIdOf: Map<number, number>,
  volumeResolved: number[][],
  surfaceResolved: number[][],
  volumeIdOf: Map<number, number>,
  surfaceIdOf: Map<number, number>,
  usedNames: Set<string>
): string[] {
  const name = sanitizeSubModelPartName(group.name, usedNames);
  const out = [`Begin SubModelPart ${name}`];

  const elementIds = group.volumeCellIndices.map((i) => volumeIdOf.get(i)!).sort((a, b) => a - b);
  const conditionIds = group.surfaceCellIndices.map((i) => surfaceIdOf.get(i)!).sort((a, b) => a - b);

  // Node-consistency rule: every node used by a grouped cell must also appear in
  // this SubModelPart's SubModelPartNodes — (explicitly-selected nodes) ∪ (all
  // nodes, incl. mid-side, of every grouped cell).
  const nodeIdSet = new Set<number>();
  for (const tag of group.extraNodeTags) {
    const id = nodeIdOf.get(tag);
    if (id !== undefined) nodeIdSet.add(id);
  }
  for (const i of group.volumeCellIndices) for (const id of volumeResolved[i]) nodeIdSet.add(id);
  for (const i of group.surfaceCellIndices) for (const id of surfaceResolved[i]) nodeIdSet.add(id);
  const nodeIds = [...nodeIdSet].sort((a, b) => a - b);

  out.push("    Begin SubModelPartNodes");
  for (const id of nodeIds) out.push(`    ${id}`);
  out.push("    End SubModelPartNodes");

  if (mode === "elements") {
    out.push("    Begin SubModelPartElements");
    for (const id of elementIds) out.push(`    ${id}`);
    out.push("    End SubModelPartElements");

    out.push("    Begin SubModelPartConditions");
    for (const id of conditionIds) out.push(`    ${id}`);
    out.push("    End SubModelPartConditions");
  } else {
    // All kinds share one Geometries id space, so a group's geometry ids are the
    // union of its volume + surface cell ids.
    const geometryIds = [...elementIds, ...conditionIds].sort((a, b) => a - b);
    out.push("    Begin SubModelPartGeometries");
    for (const id of geometryIds) out.push(`    ${id}`);
    out.push("    End SubModelPartGeometries");
  }

  out.push("End SubModelPart");
  return out;
}

/** Replaces anything but `[A-Za-z0-9_]` with `_`, prefixes a name that doesn't
 * start with a letter/underscore with `Part_`, and guarantees uniqueness among
 * siblings via a `_2`, `_3`, … numeric suffix. */
function sanitizeSubModelPartName(name: string, used: Set<string>): string {
  let base = name.replace(/[^A-Za-z0-9_]/g, "_");
  if (base === "" || !/^[A-Za-z_]/.test(base)) base = `Part_${base}`;

  let candidate = base;
  let suffix = 2;
  while (used.has(candidate)) {
    candidate = `${base}_${suffix}`;
    suffix++;
  }
  used.add(candidate);
  return candidate;
}
