import { validateMeshOptions, DEFAULT_MESH_OPTIONS, gmshShapeOptions, type MeshOptions } from "./meshOptions";

/**
 * Pure (vscode-free) parse/serialize for the mesh options sidecar
 * `<model>.mesh.json`, plus the `.geo` script generator — unit-testable.
 * Mirrors `editsSidecar.ts`. The sidecar holds the mesh generation options;
 * the source CAD file is never modified.
 */

export const MESH_SIDECAR_VERSION = 1;

interface MeshSidecarFile {
  version: number;
  source: string;
  options: MeshOptions;
}

/**
 * Parses + validates sidecar JSON into a clean {@link MeshOptions}. Tolerant:
 * falls back to {@link DEFAULT_MESH_OPTIONS} on any parse/validation failure
 * (never throws), so a hand-edited or partially-corrupt sidecar never blocks
 * meshing.
 */
export function parseMeshJson(text: string): MeshOptions {
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch {
    return DEFAULT_MESH_OPTIONS;
  }
  const rawOptions = (data as Partial<MeshSidecarFile> | null)?.options;
  const options = validateMeshOptions(rawOptions);
  return options ?? DEFAULT_MESH_OPTIONS;
}

/** Serializes options to the sidecar JSON text (pretty-printed, trailing newline). */
export function serializeMeshJson(sourceName: string, options: MeshOptions): string {
  const file: MeshSidecarFile = { version: MESH_SIDECAR_VERSION, source: sourceName, options };
  return JSON.stringify(file, null, 2) + "\n";
}

/**
 * Generates the editable `.geo` script text for GMSH: merges the source CAD
 * file, sets one `Mesh.*` option per {@link MeshOptions} field, and issues
 * the trailing `Mesh <dimension>;` command that actually triggers meshing.
 *
 * Under `engine: "ftetwild"`, the trailing `Mesh <dimension>;` directive is
 * REPLACED with a plain comment rather than emitted as usual — a `.geo`
 * script is inherently Gmsh-only (there is no fTetWild directive Gmsh's own
 * `.geo` interpreter could run), so opening this file in a real Gmsh install
 * and running it would silently mesh via Gmsh's `classifySurfaces` path
 * instead of the fTetWild tetrahedralizer this extension actually used —
 * misrepresenting what was done, not just producing a slightly different
 * result. The `Merge` + `Mesh.*` option lines still emit unchanged (they're
 * harmless, and several — `Mesh.MeshSizeMin`/`Max` — are still meaningful
 * context even though fTetWild doesn't read them via this file).
 */
export function generateGeoScript(sourceName: string, options: MeshOptions): string {
  const shape = gmshShapeOptions(options.elementShape, options.dimension);
  const lines = [
    "// Auto-generated by CAD-Preview. Edits here are not read back by the",
    "// extension; use the Meshing panel to change options.",
    `Merge "${sourceName}";`,
    `Mesh.MeshSizeMin = ${options.sizeMin};`,
    `Mesh.MeshSizeMax = ${options.sizeMax};`,
    `Mesh.Algorithm = ${options.algorithm2D};`,
    `Mesh.Algorithm3D = ${shape.algorithm3DOverride ?? options.algorithm3D};`,
    `Mesh.ElementOrder = ${options.elementOrder};`,
    `Mesh.RecombineAll = ${shape.recombineAll};`,
    `Mesh.SubdivisionAlgorithm = ${shape.subdivisionAlgorithm};`,
    `Mesh.Recombine3DAll = ${shape.recombine3DAll};`,
    `Mesh.Optimize = ${options.optimize ? 1 : 0};`,
    options.engine === "ftetwild"
      ? "// engine: fTetWild — this document was volume-meshed by fTetWild, not Gmsh's\n" +
        "// own mesher, so there is no Gmsh directive that reproduces it. Running\n" +
        `// this script's own "Mesh ${options.dimension};" would mesh via Gmsh's\n` +
        "// classifySurfaces path instead — a different result, not a re-run of\n" +
        "// what this extension actually did — so it is deliberately omitted."
      : `Mesh ${options.dimension};`,
  ];
  return lines.join("\n") + "\n";
}
